spring:
  application:
    name: auth

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      connection-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_EMAIL}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret-key: ${JWT_SECRET_KEY}
  refresh-secret-key: ${JWT_REFRESH_SECRET_KEY}
  access-token-validity-seconds: 3600  #1hour
  refresh-token-validity-seconds: 604800 #7days

server:
  port: 8083
